[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.0"
  VITE_SUPABASE_URL = "https://zkafxyjxvhgeitdzgbnn.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprYWZ4eWp4dmhnZWl0ZHpnYm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODAwMTksImV4cCI6MjA3Mzg1NjAxOX0.SfdgOcO4rdHInGgtrTl39HfBHKto1n4pxytaCNoadio"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
